spring:
  rabbitmq:
    host: 192.168.1.6
    port: 5672
    username: test
    password: 123456
    listener:
      direct:
        acknowledge-mode: MANUAL
      simple:
        acknowledge-mode: MANUAL