server:
  port: 9088
spring:
  rabbitmq:
    host: 192.168.1.6
    port: 5672
    username: test
    password: 123456
    virtual-host: /
    connection-timeout: 10000
    template:
      mandatory: true
    publisher-confirms: true
